name: Update README

on:
  schedule:
    - cron: "0 * * * *" # updates every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config: |
            template: classic
            base: header, activity, community, repositories, metadata
            repositories: 100
            commits_authoring: all
